### PR TITLE
Added additional statistics available in `threshperf(statistics=)`

### LINKED ISSUE #12: Feature Request: Add additional stats/functionality to `threshperf()`
Hello hello!

I have a couple of requests for the `threshperf()`. I am happy to implement them, but first wanted to get your feedback before preparing a pull request.
1. Add additional stats like the true positive rate, false positive, etc.
2. For case control data, add the option to specify a prevalence so statistics such as  true positive rate, false positive, etc. are calculable.
3. Adapt the function (or create a new function) that can handle time to event outcomes.

Let me know what you think!

### PR DESCRIPTION
**Pull request by ddsjoberg**
* Added additional statistics available for output in `threshperf(statistics=)`.

Other changes made (I can undo any of these if you prefer!).
* Ran `usethis::use_tidy_description()` to put DESCRIPTION file entries in standard order.
* Added a `NEWS.md` file for tracking changes.
* Added a package documentation file with `usethis::use_package_doc()`. You can now get a help file for the package `?runway-package`
* Added internal imports of functions `.data` and `.env` from the rlang package.
* The purrr package was missing from DESCRIPTION Imports section.
* Ran `usethis::use_roxygen_md()` to use roxygen2 comments to document package.
* Added unit testing framework with the testthat package and added a test for `threshperf()`

closes #12

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Hey hey @kdpsingh ! I think this pull request is now ready for review! Please let me know if you'd like to discuss.

**Comment by kdpsingh** [comment]
Excellent @ddsjoberg! Thank you so much for adding functionality and unit tests. This will be a learning opportunity for me. I'll review by tomorrow and will squash merge if all looks good.

I'll follow-up if questions.

**Comment by kdpsingh** [comment]
This looks great. We still need to do a bit of work on our end to read through and fully understand implications for using this with case-control data. As in, should the model developer adjust the predicted probabilities on their end *prior* to modeling or should this be done on the evaluation end (ie. using runway)? I think supporting this in runway is a good idea, so having checked this, will merge. 

Thank you for the contribution, @ddsjoberg!

**Comment by ddsjoberg** [comment]
Thanks @kdpsingh !

**Pull request merged**
